
#' Plot a saved superheat object.
#'
#' \code{plot.superheat} is able to plot superheat graphs.
#'
#' @param superheat.obj A superheat object, such as is generated by the
#'        superheat() function.
#' @examples
#' # plot a superheat object built for the iris dataset
#' superheat.obj <- superheat(X = iris[,-c(1, 5)],
#'                  yr = iris[,1],
#'                  yr.axis.name = "Sepal.Length",
#'                  membership.rows = iris$Species,
#'                  print.plot = F)
#' plot.superheat(superheat.obj)
#' @export



plot.superheat <- function(superheat.obj, ...) {

  plot(superheat.obj$plot)

}
